server:
  port: 30000
spring:
  messages:
    basename: messages/messages
  datasource:
    url: jdbc:postgresql://localhost:${CODEHQ_DATABASE_PORT:30001}/codehq
    username: codehq
    password: codehq
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            # The following prevents a Hibernate exception during initialisation.
            # https://stackoverflow.com/a/34289031
            non_contextual_creation: true
          time_zone: UTC

---
spring:
  profiles: docker
  datasource:
    url: jdbc:postgresql://db/codehq

server:
  port: ${SERVICE_PORT}